# Generated by Django 4.1.2 on 2022-10-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoFacturable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=100)),
                ('clase_concepto', models.CharField(max_length=45)),
                ('operador', models.CharField(max_length=45)),
                ('tipo_comunicacion', models.CharField(max_length=45)),
                ('concepto_operador', models.CharField(max_length=100)),
                ('ambito', models.CharField(max_length=45)),
            ],
        ),
    ]
